# baseURL = 'https://ddm.uem.br/'
# baseURL = 'localhost'
languageCode = 'pt-BR'
title = 'Curso de Design - Universidade Estadual de Maringá'
theme = "universal"
style = "green"

defaultContentLanguage = 'pt-BR'
defaultContentLanguageInSubdir = false
[languages]
  [languages.pt-BR]
    contentDir = 'content'
    disabled = false
    languageCode = 'pt-BR'
    languageDirection = 'ltr'
    languageName = 'Português do Brasil'
    title = 'Curso de Design - Universidade Estadual de Maringá'
    weight = 1
    [languages.pt-BR.params]
      subtitle = 'Campus Regional de Cianorte'

[params]
    disabled_logo = false
    logo_text = "Design"
    dropdown_mouse_over = true

    logo = "img/logo.png"
    logo_small = "img/logo_p.png"
    banner = "img/banner01.jpg"

    summaryLength = 70

    # date_format = "2006-01-02T15:04:05Z0700"
    date_format = "2.1.2006"

[params.carouselHomepage]
    enable = true
    auto_play = true
    slide_speed = 2000
    pagination_speed = 1000

[params.recent_posts]
    enable = true
    title = "Notícias"
    subtitle = "Algumas das novidades do curso"
    hide_summary = false

[[menu.main]]
    name       = "Principal"
    identifier = "menu.principal"
    url        = "/"
    weight     = 10


[[menu.main]]
    name       = "Institucional"
    identifier = "menu.institucional"
    # url        = "/institucional/"
    weight     = 20

### Institucional

[[menu.main]]
name       = "Sobre o curso"
parent = "menu.institucional"
url        = "/institucional/curso"
weight     = 25

[[menu.main]]
name       = "História do Campus"
parent = "menu.institucional"
url        = "/institucional/historia-do-campus"
weight     = 26


[[menu.main]]
name       = "Horários"
parent = "menu.institucional"
url        = "/institucional/horarios"
weight     = 27


[[menu.main]]
name       = "Professores"
parent = "menu.institucional"
url        = "/institucional/professores"
weight     = 29

[[menu.main]]
    name       = "Notícias"
    identifier = "menu.noticias"
    # url        = "/blog"
    weight     = 30

[[menu.main]]
    name       = "Blog"
    parent = "menu.noticias"
    url        = "/blog"
    weight     = 49

[[menu.main]]
    name       = "Clipping"
    parent = "menu.noticias"
    url        = "/clipping"
    weight     = 49

[[menu.main]]
    name       = "Alunos"
    identifier = "menu.alunos"
    url        = "/alunos"
    weight     = 50

[[menu.main]]
    name       = "Fale conosco"
    identifier = "menu.contato"
    url        = "/contato"
    weight     = 60


[params.topbar]
    enable = true
    text = "<p>Contato: (44)3619-4008</p>"

[[menu.topbar]]
    weight = 2
    name = "Instagram"
    url = "https://www.instagram.com/uemdesign/"
    pre = "<i class='fas fa-2x fa-instagram'></i>"

