name: Envio dos arquivos para o servidor
run-name: ${{ github.actor }} está enviando os arquivos para o repositório no servidor da UEM.
on: [push]
jobs:
  Entra-no-Servidor:
    runs-on: ubuntu-latest
    steps:
      - id: envio
        uses: invi5H/ssh-action@v1
        with:
          SSH_HOST: ${{ secrets.HOST }}
          SSH_USER: ${{ secrets.USER }}
          SSH_KEY: ${{ secrets.SSHKEY }}
          SSH_PORT: ${{ secrets.SSHPORT }}
      - name: Entra na pasta onde estão os arquivos do Design
        run: ssh ${{ steps.envio.outputs.SERVER }} cd "${{ secrets.PATHDESIGN }}"
      - name: Lista o conteúdo da pasta
        run: ssh ${{ steps.envio.outputs.SERVER }} ls -la 
        #   script: |
        #     cd "${{ secrets.PATHDESIGN }}"
        #     rm -rf public/*
        #     git pull
        ##     podman run --rm --name hugo-build -v "${{ secrets.PATHDESIGN }}:/src:rw"	--security-opt="label=disable" 	docker.io/jakejarvis/hugo-extended:latest 

    # steps:
    #   - run: echo "Esse é somente um teste para envio do ${{github.event_name}}"
    #   - name: Testando o repositorio
    #     uses: actions/checkout@v4
    #   - run: echo "Testando o repositório ${{ github.repository }}."
    #   - name: Listando os arquivos
    #     run: ls -la ${{ github.workspace }} 
    #   - run: echo "Somente o status do repositório ${{ job.status }}."