name: Enviar os arquivos para o servidor.
run-name:  Realizar esse envio a cada mudança do site.
on: [push]
jobs:
  Entra-no-Servidor:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar o repositório para montar os arquivos HTML.
        uses: actions/checkout@master
        with:
          submodules: true
      - name: Hugo Framework - Montagem dos arquivos estáticos.
        uses: chabad360/hugo-actions@master
      - name: Transfere os arquivos criados para o servidor.
        uses: easingthemes/ssh-deploy@v5.1.0
        with: 
            SSH_PRIVATE_KEY: ${{ secrets.SSHKEY }}
            REMOTE_USER: ${{ secrets.SSHUSER }}
            REMOTE_HOST: ${{ secrets.SSHHOST }}
            REMOTE_PORT: ${{ secrets.SSHPORT }}
            SOURCE: "public/"
            TARGET: "${{ secrets.PATHDESIGN }}"
            ARGS: '--include .htaccess --exclude ".*" --recursive --delete-excluded' 