name: Envio dos arquivos para o servidor
run-name: ${{ github.actor }} está enviando os arquivos para o repositório no servidor da UEM.
on: [push]
jobs:
  Entra-no-Servidor:
    runs-on: ubuntu-latest
    steps:
      - name: Executa um comando SSH no servidor
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSHKEY }}
          port: ${{ secrets.SSHPORT }}
          script_stop: true
          - name: Entra na pasta onde estão os arquivos do Design
            run: cd "${{ secrets.PATHDESIGN }}"
          - name: Lista o conteúdo da pasta
            run: ls -la 
        #   script: |
        #     cd "${{ secrets.PATHDESIGN }}"
        #     rm -rf public/*
        #     git pull
        #     podman run --rm --name hugo-build -v "${{ secrets.PATHDESIGN }}:/src:rw"	--security-opt="label=disable" 	docker.io/jakejarvis/hugo-extended:latest 

    # steps:
    #   - run: echo "Esse é somente um teste para envio do ${{github.event_name}}"
    #   - name: Testando o repositorio
    #     uses: actions/checkout@v4
    #   - run: echo "Testando o repositório ${{ github.repository }}."
    #   - name: Listando os arquivos
    #     run: ls -la ${{ github.workspace }} 
    #   - run: echo "Somente o status do repositório ${{ job.status }}."