name: Envio dos arquivos para o servidor
run-name: ${{ github.actor }} está enviando os arquivos para o repositório no servidor da UEM.
on: [push]
jobs:
  Entra-no-Servidor:
    runs-on: ubuntu-latest
    steps:
      - name: Copiando o repositório para montar o site
        uses: actions/checkout@master
        with:
          submodules: true
      - name: Montando o site usando Hugo
        uses: chabad360/hugo-actions@master
      - name: Faz a transferência do site inteiro para o destino
        uses: easingthemes/ssh-deploy@v5.1.0
        with: 
            SSH_PRIVATE_KEY: ${{ secrets.SSHKEY }}
            REMOTE_USER: ${{ secrets.SSHUSER }}
            REMOTE_HOST: ${{ secrets.SSHHOST }}
            REMOTE_PORT: ${{ secrets.SSHPORT }}
            SOURCE: "public/"
            TARGET: "${{ secrets.PATHDESIGN }}"
            ARGS: '--include .htaccess --exclude ".*" --recursive --delete-excluded -P' 